### ISSUE TITLE
Use Github Discussions, when this feature is available

### ISSUE THREAD

**Issue by guettli** [guettli/programming-guidelines#10]
AFAIK this is not available yet.

**Comment by emmysteven** [comment]
I beg to differ, this feature is already available 😊

Here is how you can activate it on this repository, if you don't mind 🙏

1- Go to the settings tab on this repository like so
![image](https://i.ibb.co/9nYtvBB/Screen-Shot-2020-12-15-at-6-19-41-PM.png)


<br><br>

2- Then tick the **Discussions** square button and after that click on **Set up discussions**
![image](https://i.ibb.co/Rcm03Zc/Screen-Shot-2020-12-15-at-6-21-38-PM.png)

<br>

Congratulations!, there you have it, you have now activated the discussions tab for this repository

Cheers!

**Comment by guettli** [comment]
Thank you! I was blind. Now you discussions are available: Feel free to write the first message: https://github.com/guettli/programming-guidelines/discussions
