### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Matt-Deacalion** [guettli/programming-guidelines#14]
This is a good idea. I really like the pragmatic approach, which is refreshing
to see in a tech world that is (to my mind) taking more and more to
naval-gazing and adding layers of complexity without considering it's price.

I'm not sure if these are common enough to warrant consideration by others, but
I find that most of my issues are psychological. I don't find technical things
difficult, but achieving the mind state where I can consistently deliver high
value work can be. In that sense what ever I'm working on becomes a canvas -
which reflects my mental state - perfectionism, laziness, fears, doubts. If I
lose my attention, my diligence… everything technical goes with it.

## Distraction
Inner tension makes distractions attractive. Distraction comes in many forms…
and some of those can appear "productive". Don't get emotionally tangled in
them - see them as curiosities and be creative in regaining attention.

## Mindfully Choose Your Metrics
The metrics you track influence the way you think. They're created by people
and they express what people think is important - choose them mindfully.

related: "When a measure becomes a target, it ceases to be a good measure."

## Do
Nothing is scary, don't labour towards making it so. If something feels
overwhelming, adjust your thinking (or evaluate if the trade-off is worth it).
Everything you see was built on a mountain of mistakes.

related: "Knowledge is only a rumour until it lives in the muscle."

## Complexity is Inefficient
Nothing is free, everything is a trade. Before adding something, try removing
something - or take a step back and see if there's a higher solution. Problems
can disappear through good design.

## Know Why Things Are There
Don't allow anything in your tech stack or development process until you know
"why" it should be there. This doesn't mean you have to entirely understand
"how" it works.

## Know the "h07 73chzor" Crowd
A few years back it wasn't uncommon to get flak for using a relational database
instead of a NoSQL one. Today you may face "REST? Why no GraphQL?!"… tomorrow
it may be "Ha! You're still using Python 15?". Not all that is new is
progress, or the right fit for your needs. Hold onto and refine your judgement;
you're not a backwards "reactionary" for evaluating things from your own
perspective. Don't be "noob" or tech shamed.

related: cargo culting

## Technologies Have Personalities
When evaluating a tech, pay attention to the nature and tone of it's community,
are their priorities in line with yours? Some tech seems to be designed to
sell conference tickets and learning courses - be aware of tech that's in the
business of making work for itself.

When choosing a tech, you're choosing a tone. You're choosing how you will
communicate to other developers. You're choosing a shared mental model.

Example:
- I chose Django for it's pragmatism and it's community's respectful nature
  (on the flip-side, I avoided JavaScript until ES6 because it felt more
  like fashion than engineering).
- I chose Vue over React because I saw less dogma, no fetish for tooling
  and a community intent on lowering the barrier to entry.

related: take evangelist's claims with a healthy dose of skepticism.

## The Cult of Correct
Correct doesn't exist. There are no universal laws on what is appropriate.
Every decision is a trade that's either optimal or suboptimal.

## Other
- Learn the command line
- Try out a tiling window manager for a month or two
- Silicon Valley doesn't have the same constraints as the rest of the world,
  bear that in mind when evaluating the "solutions" they offer

## Agree
- I hate shell scripts. This looks promising: https://www.oilshell.org/
- "aaa tests" - I use `marks`, e.g. `@pytest.mark.xxx` for the set of tests I'm
  working on, and `@pytest.mark.current` for the individual one I'm working on…
  then I do `pytest -m xxx` or `pytest -m current`.
- "Is config code or data?" Additionally: an advantage of config in the
  database is it doesn't require deployment to change something, whereas an
  advantage of config in the code is it can make it easier to test.
- "ForeignKey from code to DB" - there's a nice Django app called `django-solo`
  that's useful when you have a single-row configuration.
- "Statistical Profiler" thank you!
- "Calendar Versioning" thank you!
- "Architectural Decision Records" thank you!

## Disagree

- Vue. Personally, it's proven to be a great tool for delivering projects;
  it manages complexity well and feels like Django for the frontend. Vue's
  form, value and function fits my team's needs well. Yes, cargo culting
  happens everywhere, but Vue does provide significant value. That said,
  retooling is hard, and should be reserved for occasions that demand it
  (if you want to know more about our setup, let me know).

  The frustration I have is more towards frontend in general: the dogma,
  the overwhelming concern with minutiae, the neuroticism, the churn, the
  obsession with tooling, the detachment from real life constraints etc.

- Vim. I like the separation between "modes" - my actions become more
  precise and disciplined because I'm forced to pause before I do
  something. Every action becomes a meditation. My flow for manipulating
  text files now resembles a form of grammar. When I use a non-modal editor
  I feel like I'm working with an unruly crayon. And, if you use `coc.vim`
  you can use any extension that VSCode has. Yes, it's old - and it's not
  for everyone, but it's time has certainly not "passed".

## Questions

1. I have the same initial impression of Kubernetes as you do with Vue
   (bloated, cargo cultish) - since you lean towards simplicity, what led you
   to use it? what was the overhead in learning it? And do you think it was
   worth it?
2. In "Use http, avoid ftp/sftp/scp/rsync/smb/mail", "Why is HTTP better?
   Because HTTP can validate the data." - I don't follow. Let's say I have an
   API that uses `django rest framework` - so I push data through the API, is
   the validation part running a `serializer`? and if I used `rsync` to dump a
   `.json` file I'm effectively throwing data into my app via a backdoor?

**Comment by guettli** [comment]
Thank you for your feedback.

> Some tech seems to be designed to
> sell conference tickets and learning courses - be aware of tech that's in the
> business of making work for itself.

haha, this made me smile. Thank you :-)


> I have the same initial impression of Kubernetes as you do with Vue
> (bloated, cargo cultish) - since you lean towards simplicity, what led you
> to use it? what was the overhead in learning it? And do you think it was
> worth it?

Four years ago I had a first look at Kubernetes. I liked it, but I  had no use-case.
Then two years go I had a second look. But at this time many things where not settled yet.
Some weeks ago I had the third look at it, and I think that it is now time to learn it.
I have not real-world experience yet, but I will make a Cert via linux-foundation soon.
I can tell you if it was worth it in three years :-)



> In "Use http, avoid ftp/sftp/scp/rsync/smb/mail", "Why is HTTP better?
> Because HTTP can validate the data." - I don't follow. Let's say I have an
> API that uses django rest framework - so I push data through the API, is
> the validation part running a serializer? and if I used rsync to dump a
> .json file I'm effectively throwing data into my app via a backdoor?

You can validate the data which the DRF API receives. And if the data is not valid,
you can reject the data. If you are sending and receiving the data the issue is minor.
But if the sender is a different company, then it is an issue. 
If you receive invalid data via ftp/rsync. Then you have dirty stuff on our side.
And then you are somehow responsible to communicate to the sender that
the dirty stuff can't be imported. I don't have this issue anymore since I 
don't run data imports via rsync/ftp now.

I agree to your text about mental state and productivity. You can't be productive 24 hours per day. And the mind likes cherry-picking. This means you need to hit yourself in the ... somehow to work for long-term goals.

Feel free to ask further questions.

Please tell me if you find typos or other things to improve. PR are very welcome.

**Comment by Matt-Deacalion** [comment]
> haha, this made me smile. Thank you :-)

Inspired (_stolen_) by Charles Dickens - "The one great principle of the English law is, to make business for itself".

> I can tell you if it was worth it in three years :-)

Haha, would be great to see your perspective as you learn and implement it.

>  This means you need to hit yourself in the ... somehow to work for long-term goals.

Absolutely, and the need for structure to go after big things becomes more and more apparent as you go on.

I appreciate the response, thank you.

**PS**: I see you're using HTMX, [petite-vue](https://github.com/vuejs/petite-vue) seems to be in a similar vein - might be of interest.
