### ISSUE TITLE
csv

### ISSUE THREAD

**Issue by BMaxV** [guettli/programming-guidelines#18]
Hi I read your guidelines, lots of things I like, some parts I would have liked to know earlier, some parts I don't understand since I haven't encountered them. Which I take as a good sign, the advice giving has happened before the problem.

Anyway, the one thing I disagree about is csv. I like csv because it's an easy format that I can write and parse myself. Reading Excel directly is better but may not be available.

It also means someone is using excel.

Failure on my part to read the csv means there is either something wrong with the data I need to fix anyway or I didn't understand something or both. All are good if they happen when I read the file, as opposed to when I try to use the data.

Anyway thanks for this text, I'm sure it will be useful in the future.

**Comment by guettli** [comment]
thank you for your feedback. Feel free to open a new issue if something is not clear to you. Just ask!
