### ISSUE TITLE
My simple feedback

### ISSUE THREAD

**Issue by hynekcer** [guettli/programming-guidelines#2]
I'm misusing issues for a friendly feedback. I agree with you if I can judge at all or I have a similar intuition or believe something could be well-founded (like don't use XY) and the life is short.

a piece of trash in: "Imagine there is be a a Meta"

"Conditionless Data Structures" - Yes. A good example is a donation from "unknown donor" (imagine in a NGO) It allows more clear queries and statistics, but paradoxical more conditions in the code to not allow to update that general "unknown" object by mistake when some information became known later.

Null values: Nulls are also a big problem in Numpy and Pandas. If an integer or boolean field contains a NULL then the column is converted to float numbers, or is invalid without Pandas. Many people consider special rules and values like NaN, -inf, +inf a lapsus in IEEE 754. If a modern float point processor contains such value anywhere in FPU Register Stack then reportedly it still operates twenty times slower until that thrown out.

Constraints x redundancy: I agree. A special case "are historical" data that should be never synchronized, e.g. foreign key to contact on invoice object and a name of subject at the when the invoice was created.

CRD: Delete is also problematic, especially if the object is still used as a foreign key, e.g. a Contact. Update can not be replaced by delete+create then. (The only point where I rather disagree.)

CSV vs Excel: agree. Huge Excel files can be many times slower than the same data in CSV. This can be the only reason to convert, if the same file must be used repeatedly.

Give booleans a "positive" name: That means sometimes to use a default value True (checked box).

Untestable code: I agree: write test or simplify to be testable. I remember my fix to a bug in Django createsuperuser that failed only on Windows if the current user username contained some accent characters. The fix has not been merged because it was essentially untestable (many possible windows versions and regions) The code and fix was simplified to slugify the username only, where everything can either be tested or considered unbreakable.

Don't search the needle...: I like to add a debug condition or debug print to the right place in Django source code in a similar situation. (But maybe I will not know it in next versions and I write to my list: Don't maintain a custom Django db backend :-)

Love your docs (readme friendly to newcomers) !!!
Avoid to get a nerd !!! very important

Thank for sharing this with me.

**Comment by guettli** [comment]
Hi Hynek,

thank you for your feedback.

I am happy that you agree with most of the hints in the guideline.

I don't understand this. Could you please elaborate?

> a piece of trash in: "Imagine there is be a a Meta"



> Update can not be replaced by delete+create then

Yes, you are right. I think about how to rewrite this part.

Again, thank you. I hope we see us again on StackOverflow or in real life.

**Comment by hynekcer** [comment]
I wrote "typo" originally, but it is less than typo, it is a residue of edit between "Imagine there is a Meta..." to/from "Imagine there would be a Meta..." not cleaned... and you wrote about wiping the dust. That was my association.

> Update can not be replaced by delete+create (not at all sometimes)

CRD: A very noticeable example is a Contact or User or any object that is usually a foreign key of many posts, support cases, invoices etc. because it would break other data and cause much more problems, including race condition problems, than it could solve. I know that an equivalent of Delete must be implemented due to the "GDPR right to be forgotten". Imagine that I or you would require that on SOverflow (virtual euthanasia?) how many answers to related questions would be lost if they are not reparented to [community](https://stackoverflow.com/users/-1/community) = user(-1) as the last possibility. Sometimes Delete must be probably postponed after appeal period and time for necessary steps if the user is an employee. Only updates active=False (can not login), freeze=True (can't be assigned as owner of new objects) etc. are possible immediately. If an object is a root of hierarchy then delete is the most critical operation, not update.

You probably think at CRD about leaves in the relationship tree, with less important data where is accepted a risk of race condition or data loss (risk of delete without create e.g. a network problem before create) and the main criterion is simplicity. Then I understand "sometimes CRD helps".

**Comment by guettli** [comment]
Thank you for your feedback. I think I will leave the text as it is. AFAIK I did not say that CRUD can be always simplified to CRD. ... I read my text again. Yes, I say "Sometimes CRD helps". At least in PostgreSQL a ForeignKey constraint will raise if you want to delete data that is still referenced.

I close this. Please write again, if you think something is missing or wrong.
