### ISSUE TITLE
Shell scripting

### ISSUE THREAD

**Issue by ionelmc** [guettli/programming-guidelines#4]
When talking about shell scripting I always point people to https://mywiki.wooledge.org/BashPitfalls - it has a comprehensive list of ways you can destroy a machine with seemingly harmless shell scripting. Might want to give a link to that or at least include some common sense practices (`set -eu`, `[[` over `[`/`test` and such)?

PS. Very solid guide. How much time did you spend on it?

**Comment by guettli** [comment]
Thank you for the link. I added it.

How much time? 5 Minutes twice a week.

A lot of things come up if I cycle from work to home. I stop, write a very small mail to myself to keep the idea alive. Later I add it or discard it.

**Comment by guettli** [comment]
@ionelmc the best way to avoid pitfalls in shell scripts is to avoid shell scripts :-)

Please ask new questions! I am always looking for feeback.

I close this one. Please open new issues - I will respond.
