### ISSUE TITLE
Food for thought?

### ISSUE THREAD

**Issue by pmav99** [guettli/programming-guidelines#6]
Maybe you will find this interesting + you might want to include some of the topics in your own guideline: https://github.com/theodesp/stable-systems-checklist

PS. Thanks for the awesome guide :)

**Comment by guettli** [comment]
I am happy, that you like it.

May I ask some questions?

Where did you stumble upon this page?

What do you like the most?

Where do you think something is wrong?

**Comment by emmysteven** [comment]
Reading your guideline has tremendously added value to me
I stumbled upon this page via a [forked repo](https://github.com/unclebay143/programming-guidelines)
This is the one I love the most
```
Code is always testable, there is no untestable code.
Maybe your knowledge of testing is limited up to now. 
Finding untestable code and making it testable is the beginning of an interesting adventure.
``` 
As in all things, there is alway room for improvement and to that, I raised an issue #9 
Above all, it was a wonder piece, please keep it up 👍🏻

**Comment by guettli** [comment]
@emmysteven thank you for this idea. Yes, github discussions would make sense. I created a new ticket for this: https://github.com/guettli/programming-guidelines/issues/10

Please provide more feedback. Up to now only few people dared to speak up. What else could get improved?
