### ISSUE TITLE
Fix grammatical mistakes and typos found in README.md

### ISSUE THREAD

**Issue by emmysteven** [guettli/programming-guidelines#9]
Hello! 👋🏻
I wanted to discuss this before opening a pull request.

Your guideline has help me tremendously and want to say a big thank for sharing this information free of charge.
However I found some grammatical mistakes and typos on some segments, and I would love to point out a few with their corresponding corrections.

**purpuse** this typo can be found under this heading [make-a-clear-distinction-between-authentication-and-permission-checks](https://github.com/guettli/programming-guidelines#make-a-clear-distinction-between-authentication-and-permission-checks)
```diff
-- purpuse
++ purpose
```
**immideately** this typo can be found under this heading [FTUE](https://github.com/guettli/programming-guidelines#ftue)
```diff
-- immideately
++ immediately 
```

**Idempotence is great, since it ensures, that it does not do harm if the method is called twice.** this issue is found under this segment [idempotence-is-great](https://github.com/guettli/programming-guidelines#idempotence-is-great)
```diff
-- Idempotence is great, since it ensures, that it does not do harm if the method is called twice.
++ Idempotence is great, since it ensures that no harm is done if the method is called twice.
```

These are the ones I could spot out for now.
Do I have the permission to effect these corrections and many others and then create a pull request? 🙏

**Comment by guettli** [comment]
@emmysteven  thank you very much for your input. This motivated my to do something which I have planed since several month: I checked the whole text with Grammarly. Could you please have a look again at the text. I think I changed about 600 mistakes which Grammarly detected.

**Comment by guettli** [comment]
If you find a mistake, please create a pull request. Thank you!

And if you like it, then please share it!

**Comment by emmysteven** [comment]
Thank you for your response

I'll do as you have said, If I find any mistake, I'll create a pull request.

Cheers!
